preprocess_function: format_openmathinstruct2
new_cache_dir: /raid/s3/opengptx/behzad_shomali/custom_hf_cache/
train_size: 300000
val_size: 0.01
random_seed: 2000
model_name: Behzadshomali/Teuken3.7B

learn_embed: True
learn_normalization: True

sft:
  output_dir: /raid/s3/opengptx/behzad_shomali/instruction_tuning/
  
  eval_accumulation_steps: 1

  num_train_epochs: 1
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 8
  gradient_checkpointing: False
  max_length: 1024
  optim: adamw_torch_fused
  learning_rate: !!float 1e-5
  completion_only_loss: False
  assistant_only_loss: False
  max_grad_norm: 3.0

  dataloader_num_workers: 12
  # dataloader_pin_memory: False
  save_only_model: True

  lr_scheduler_type: linear
  # lr_scheduler_kwargs: 
  #   min_lr: !!float 1e-5

  weight_decay: 0.5
  warmup_steps: 150

  fp16: False
  bf16: True
  tf32: False
  
  packing: True
  use_liger_kernel: False
  
  do_eval: True
  eval_on_start: True
  logging_steps: 20
  eval_steps: 400
  eval_strategy: steps
  save_strategy: steps
  save_total_limit: 4
  save_steps: 2000
  report_to: wandb
  push_to_hub: False

  metric_for_best_model: eval_sacrebleu
  greater_is_better: True
  load_best_model_at_end: False
  disable_tqdm: False

peft:
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
  target_modules: [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "up_proj",
    "down_proj",
    "gate_proj"
  ]
  use_rslora: True

datasets:
  - is_in_HF: True
    name: nvidia/OpenMathInstruct-2
    split: train_1M
    instruction_col: problem
    response_col: generated_solution
    remove_columns: ['problem', 'generated_solution', 'expected_answer', 'problem_source']
    weight: 0.97
  # - is_in_HF: True
  #   name: openai/gsm8k
  #   split: train
  #   subset: socratic
  #   instruction_col: question
  #   response_col: answer
  #   remove_columns: ['question', 'answer']
  #   weight: 0.70

  # - is_in_HF: True
  #   name: nlile/hendrycks-MATH-benchmark
  #   split: train
  #   instruction_col: problem
  #   response_col: solution
  #   remove_columns: ['problem', 'solution']
  #   weight: 0.20

  # - is_in_HF: True
  #   name: alespalla/chatbot_instruction_prompts
  #   split: train
  #   instruction_col: prompt
  #   response_col: response
  #   remove_columns: ['prompt', 'response']
  #   weight: 0.07

  # - is_in_HF: True
  #   name: HuggingFaceTB/smoltalk2
  #   subset: SFT
  #   split: Mixture_of_Thoughts_science_no_think
  #   # instruction_col: problem
  #   # response_col: solution
  #   remove_columns: ['chat_template_kwargs', 'source', 'messages']
  #   weight: 0.2
  
  - is_in_HF: False
    name: /raid/s3/opengptx/behzad_shomali/instruction_tuning/data/code_alpaca_20k.json
    split: train
    instruction_col: instruction
    response_col: output
    remove_columns: ['instruction', 'output']
    weight: 0.03
  

wandb:
  project: Teuken3.73T_IT_OpenMathInstruct-2
  name: test