eval_device: 7
datasets:
- instruction_col: problem
  is_in_HF: true
  name: nvidia/OpenMathInstruct-2
  random_seed: 2000
  remove_columns:
  - problem
  - generated_solution
  - expected_answer
  - problem_source
  response_col: generated_solution
  split: train_1M
  test_split_ratio: 0.01
  weight: 1
learn_embed: true
learn_normalization: true
model_name: /raid/s3/opengptx/behzad_shomali/hf_converted/math-rec_2-3-5__4-7-10__-2025-10-16__13-47-59
new_cache_dir: /raid/s3/opengptx/behzad_shomali/custom_hf_cache/
preprocess_function: format_openmathinstruct2
random_seed: 2000
sft:
  assistant_only_loss: false
  bf16: true
  completion_only_loss: false
  # dataloader_num_workers: 4
  disable_tqdm: false
  do_eval: true
  eval_accumulation_steps: 1
  eval_on_start: true
  eval_steps: 500
  eval_strategy: steps
  fp16: false
  gradient_accumulation_steps: 8
  gradient_checkpointing: true
  greater_is_better: true
  learning_rate: 3.0e-05
  load_best_model_at_end: false
  logging_steps: 20
  lr_scheduler_type: cosine
  max_grad_norm: 0.1
  max_length: 1024
  metric_for_best_model: eval_sacrebleu
  num_train_epochs: 1
  optim: paged_adamw_8bit
  output_dir: /raid/s3/opengptx/behzad_shomali/instruction_tuning/math-rec_2-3-5__4-7-10__-2025-10-16__13-47-59/
  packing: true
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 4
  push_to_hub: false
  report_to: wandb
  save_only_model: true
  save_steps: 1000
  save_strategy: steps
  tf32: false
  use_liger_kernel: false
  warmup_ratio: 0.1
  weight_decay: 0.01
  save_total_limit: 30
train_size: 990000
val_size: 10000
wandb:
  project: Recursive_IT_OpenMathInstruct-2
  name: math-rec[2, 3, 5]-[4, 7, 10]-2025-10-16

