settings:
  src_path: .../XXX.jsonl
  dst_path: .../XXX.pbin
  index_path: .../XXX.idx
  jq_pattern: .text
  num_cpus: ${node_env:num_cpus}
  eod_token: 'null'
  processing_batch_size: 1000
  raw_samples_queue_size: 300
  processed_samples_queue_size: 300

tokenizer:
  component_key: tokenizer
  variant_key: pretrained_hf_tokenizer
  config:
    pretrained_model_name_or_path: Eurolingua/Modalities_8B_3.73T
    padding: false
    truncation: false